### PR TITLE
Fix/ssd1306 orientation

### PR DESCRIPTION
**Pull request by C47D**
supersedes #25

### CODE REVIEW

**Comment by C47D** [comment]
@VedantParanjape can you try this PR? It's based on your suggestions

**Comment by VedantParanjape** [comment]
Hi @C47D the rotation part works, but the display is messed up. Check the attached video. I rolled back to master and it worked normally. I see you have rewritten the driver, maybe something went aloof there.


Uploading VID_20210127_143302.mp4…

**Comment by C47D** [comment]
Weird, I tested the PR with the monochrome displays demo project using both orientations. Can you attach the generated `sdkconfig.h` file? You can find it in `build\config` on your project directory.

**Comment by VedantParanjape** [comment]
@C47D Here's the sdkconfig.h file: https://pastebin.com/9nxLtkCG

**Comment by C47D** [comment]
The only part I've changed on the driver update was the rounder callback, can you change it so it looks like this?

```c
void ssd1306_rounder(lv_disp_drv_t * disp_drv, lv_area_t *area)
{
    uint8_t hor_max = disp_drv->hor_res;
    uint8_t ver_max = disp_drv->ver_res;

    area->x1 = 0;
    area->y1 = 0;
    area->x2 = hor_max - 1;
    area->y2 = ver_max - 1;
}
```

**Comment by VedantParanjape** [comment]
@C47D It worked fine with the changes you asked me to do, please merge them into the fix branch.

Thanks for the help, I'll close this issue once the changes are merged.

**Comment by C47D** [comment]
So, let's recap, when not using the mono theme the above patch works. How are you configuring the LVGL working buffers?

**Comment by C47D** [comment]
@VedantParanjape Can you set the theme to mono?

@embeddedt is it possible to use non mono theme on monochrome display, I mean, does it change anything compared to mono?

**Comment by VedantParanjape** [comment]
> So, let's recap, when not using the mono theme the above patch works. How are you configuring the LVGL working buffers?
> 
> **EDIT**
> When using the mono theme, the LVGL work buffers size need to be in pixels, that's why `DISP_BUF_SIZE` is divided by 8. So maybe there's something we're missing in the work buffer configuration.

I have tested these changes on mono theme too, it works fine. Here's the sdkconfig: https://pastebin.com/Ah2FTUVZ

**Comment by kisvegabor** [comment]
> is it possible to use non mono theme on monochrome display, I mean, does it change anything compared to mono?

Yes, it's possible, but it might be unreadable. E.g. black text on black background in the result.

**Comment by VedantParanjape** [comment]
> > is it possible to use non mono theme on monochrome display, I mean, does it change anything compared to mono?
> 
> Yes, it's possible, but it might be unreadable. E.g. black text on black background in the result.

It worked fine on mine. But turning on monotheme, resulted in a inverted image. Can we actually turn all these options for monochrome displays ? It creates confusion.

**Comment by C47D** [comment]
Those options are handled by the primary and secondary colors on the LVGL config. We can add a help text on them tho.

**Comment by VedantParanjape** [comment]
> Those options are handled by the primary and secondary colors on the LVGL config. We can add a help text on them tho. Primary should be set to 0x000000 and secondary to 0xFFFFFF for turned off pixels background and turned on pixels for text.

Ohh, I see. When will this be merged into master branch ?

**Comment by C47D** [comment]
I've opened the PR here https://github.com/lvgl/lvgl/pull/2048
@VedantParanjape Is it possible for you to use the mono theme?

**Comment by VedantParanjape** [comment]
> The only part I've changed on the driver update was the rounder callback, can you change it so it looks like this?
> 
> ```c
> void ssd1306_rounder(lv_disp_drv_t * disp_drv, lv_area_t *area)
> {
>     uint8_t hor_max = disp_drv->hor_res;
>     uint8_t ver_max = disp_drv->ver_res;
> 
>     area->x1 = 0;
>     area->y1 = 0;
>     area->x2 = hor_max - 1;
>     area->y2 = ver_max - 1;
> }
> ```
> 
> Also, I've considered the `DISP_BUFFER` size for the mono theme (according to the `sdkconfig.h` you are using the material theme), that's why the `LV_VER_RES_MAX` is divided by 8, can you remove that division? it's here (lvgl_helpers.h), it should look like this:
> 
> ```c
> #elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_SSD1306
> #define DISP_BUF_SIZE  (LV_HOR_RES_MAX*LV_VER_RES_MAX)
> ```

@C47D I meant when will these changes be merged?

Yes, I'll just use the mono theme.

**Comment by C47D** [comment]
6b0fd1f should fix your issue, can you test it?

**Comment by VedantParanjape** [comment]
@C47D As soon as I turn on mono theme in menuconfig, again the screen starts to misbehave. changing back to material theme, it works fine.

**Comment by C47D** [comment]
Yes, that is from an old commit, it should be modifying the y coordinate, I will update it later, I'm in a bus rn.

**Comment by C47D** [comment]
What orientation are you working on?

**Comment by C47D** [comment]
I can't replicate your issue, I've tested the `lv_port_esp32` project with both landscape and landscape inverted orientations. Let me merge this and open a new issue with the minimal code to replicate your issue.

**Comment by VedantParanjape** [comment]
> I can't replicate your issue, I've tested the `lv_port_esp32` project with both landscape and landscape inverted orientations. Let me merge this and open a new issue with the minimal code to replicate your issue.

I am using landscape orientation. I have debugged this issue. Orientation doesn't cause a problem but using mono-theme does.

**Comment by C47D** [comment]
I'm testing in mono theme, both landscape and inverted landscape.
I will not be available until next week.

**Comment by VedantParanjape** [comment]
> I'm testing in mono theme, both landscape and inverted landscape.
> I will not be available until next week.

Ohk, no problem. Let me know how it goes.

Happy Holidays !

**Comment by C47D** [comment]
Will handle this later today 😄

**Comment by C47D** [comment]
@VedantParanjape Can you confirm it's working as expected?

**Comment by VedantParanjape** [comment]
@C47D Mono theme is still causing issues, there's a white static screen now, like it was on those old CRT TV's when nothing was plugged in.

Is this something to do with the buffer size ?

**Comment by C47D** [comment]
Hi, sorry I don't have a dev kit with me, can you try removing the `/8` from the `DISP_BUF_SIZE` definition?

```
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_SSD1306
#if defined (CONFIG_LV_THEME_MONO)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * (LV_VER_RES_MAX / 8))
#else
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)                                                                                                                                                                                  #endif                                    
```

**Comment by C47D** [comment]
@VedantParanjape think I found the issue, see https://github.com/lvgl/lv_port_esp32/commit/c1dc3330dde14b02252b25f31ae3c91a6afc68f5

**Comment by VedantParanjape** [comment]
@C47D Sorry to trouble you again, the static screen went away, but now the screen won't change at all. I have attached showing behaviour using mono and material theme

**Material Theme**
https://streamable.com/pvg6pd

**Mono Theme**
https://streamable.com/361d90

**Comment by C47D** [comment]
Don't worry, we're here to help.

 Is there a way for me to replicate your code?
Are you creating multiple screens and transition between them when you press the button?

**Comment by VedantParanjape** [comment]
```
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_SSD1306
#if defined (CONFIG_LV_THEME_MONO)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * (LV_VER_RES_MAX / 8))
#else
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)                                                                                                                                                                                  #endif                                    
```
Removing the `/8` solved the issue and thus the mono theme works fine now. I have sent you read access to my repository, check your mail.

**Comment by C47D** [comment]
I've solved the `/8` issue with this commit https://github.com/lvgl/lv_port_esp32/commit/c1dc3330dde14b02252b25f31ae3c91a6afc68f5 , the `size_in_px` needs to be multiplied by 8.

**Comment by VedantParanjape** [comment]
> I've solved the `/8` issue with this commit [lvgl/lv_port_esp32@c1dc333](https://github.com/lvgl/lv_port_esp32/commit/c1dc3330dde14b02252b25f31ae3c91a6afc68f5) , the `size_in_px` needs to be multiplied by 8.

I don't see the change

**Comment by C47D** [comment]
For monochrome displays (mono theme) we can group 8 pixels in 1 byte, that's why we don't really need to have `DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)`, we're wasting memory there.

**Comment by kisvegabor** [comment]
I think the root of the issue is that `lv_disp_buf_init` needs the buffer size in pixels. So it should look like this:
```c
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)

...

uint8_t disp_buf[DISP_BUF_SIZE / 8] //In case of monochrome displays when "set_px_cb" is set

...

lv_disp_buf_init(&disp_buf1, disp_buf, NULL, DISP_BUF_SIZE); //As the buffer has that many pixels
```

**Comment by VedantParanjape** [comment]
@kisvegabor I can't understand one thing, why this wierd behaviour ?

```c
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)

...

uint8_t disp_buf[DISP_BUF_SIZE / 8] //In case of monochrome displays when "set_px_cb" is set

...

lv_disp_buf_init(&disp_buf1, disp_buf, NULL, DISP_BUF_SIZE); //As the buffer has that many pixels
```

Compiles alright but this doesn't

```c
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)/8

...

uint8_t disp_buf[DISP_BUF_SIZE] //In case of monochrome displays when "set_px_cb" is set

...

lv_disp_buf_init(&disp_buf1, disp_buf, NULL, DISP_BUF_SIZE); //As the buffer has that many pixels
```

Isn't it doing the same thing ?

**Comment by VedantParanjape** [comment]
Aah, I understand know, but this is unnecessarily complex, maybe it can be simplified :)

**Comment by C47D** [comment]
@VedantParanjape don't worry, I think it's complicated because we're trying to support multiple displays of all kinds. Thanks for the patience.

**Comment by VedantParanjape** [comment]
@C47D when will the submodulebe updated in the main repository ?

**Comment by C47D** [comment]
It was updated yesterday after merging this PR, are you having any problems?

**Comment by VedantParanjape** [comment]
> It was updated yesterday after merging this PR, are you having any problems?

Oh, just saw. No problems, works all right.

**Comment by C47D** [comment]
Sure, I will over the weekend, I need to test some new LVGL capabilities ;)

**Pull request merged**
