### PR TITLE
Fix SPI configuration for ESP32C3 and ESP32S2

### PR DESCRIPTION
**Pull request by arktrin**
ESP32-C3 and ESP32-S2 don't have VSPI or HSPI. Also ESP32-C3 don't have any specific name for SPIs.

### CODE REVIEW

**Comment by C47D** [comment]
Thanks for the request @arktrin, it does look good to me, I've also requested a review from @tore-espressif .

**Review by C47D — APPROVED** [review]

**Comment by tore-espressif** [comment]
Hello @arktrin , thank you very much for your contribution.

Yes, the SPI naming is a little messy. I think we might unify it across targets (esp32, s2, s3, c3...) and use [basic SPI names](https://github.com/espressif/esp-idf/blob/master/components/hal/include/hal/spi_types.h#L24).
Because, the already deprecated prefixed SPI names (HSPI, VSPI, FSPI) are for historical reasons defined only for esp32 and esp32s2, see https://github.com/espressif/esp-idf/blob/master/components/hal/include/hal/spi_types.h#L24

This would make it future-proof and a lot easier in `menuconfig` .

Let me know what you think

**Comment by arktrin** [comment]
Hello @tore-espressif ! I do agree that SPI names (HSPI, VSPI, FSPI) are kind of confusing. So you won't approve my pull request? I did not get it :) Despite of .../hal/spi_types.h I still cannot find any reference on HSPI for ESP32-S2 in the datasheet.

**Comment by tore-espressif** [comment]
Hi, thanks for the quick response.

Yeah, I wouldn't recommend merging in this form. So the question is whether you are willing to 'bring this to perfection' (using `SPIx_HOST` macros, OR I should take over and finish it :)

**Comment by arktrin** [comment]
Ok, I will do it.

**Comment by arktrin** [comment]
@tore-espressif I've replaced specific SPI names with SPIx_HOST. Tested on my ESP32-C3 + ST7789 display board.

**Comment by tore-espressif** [comment]
Great work, let's wait for @C47D and we can merge.

---

@C47D : In retrospect, the idea with `develop` branch has not really filled up it expectations, as most PRs from community target `master`, which created conflicts between `master` and `develop` branches. I think we can merge `develop` into `master` and abandon the idea. What is your opinion?

**Review by tore-espressif — APPROVED** [review]

**Comment by tore-espressif** [comment]
Created #146 to track this.

Merging now

**Comment by tore-espressif** [comment]
This breaks scenario when SPI is shared for display and touch. (some HSPI and VSPI macros were not renamed)
I'll prepare a hotfix in #147

**Comment by arktrin** [comment]
Looks like #147 is not going to be happened. I can try to fix here other HSPI and VSPI macros issue.

**Comment by tore-espressif** [comment]
You can cherry-pick this commit https://github.com/lvgl/lvgl_esp32_drivers/pull/147/commits/d0eca96cd701261ac6c192769cd543e8878a14e7

**Comment by arktrin** [comment]
Looks like d0eca96 is doing well. So I don't think my help will be needed right now. I  don't understand what is going on with #147.

**Comment by arktrin** [comment]
Well, this story is still not finished yet :(
As of [ESP32-C3 datasheet v1.1](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf#page=20) (page 20): 
```
ESP32-C3 features three SPI interfaces (SPI0, SPI1, and SPI2). 
SPI0 and SPI1 can only be configured to operate in SPI memory mode,
while SPI2 can be configured to operate in both SPI memory and general-purpose SPI modes.
```
As of [online documentation on ESP32-C3](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/spi_master.html):
```
ESP32-C3 integrates 3 SPI peripherals.
SPI0 and SPI1 are used internally to access the ESP32-C3’s attached flash memory. 
Both controllers share the same SPI bus signals, and there is an arbiter to determine 
which can access the bus. Currently, SPI Master driver does not support SPI1 bus.
```
So at least there is no such thing as SPI3 and `SPI3_HOST` for ESP32-C3, though online docs have this somehow:
```
enum spi_host_device_t
Enum with the three SPI peripherals that are software-accessible in it.
Values:
SPI1_HOST = 0
SPI1.
SPI2_HOST = 1
SPI2.
SPI3_HOST = 2
SPI3.
```
As of [spi_types.h from esp-idf](https://github.com/espressif/esp-idf/blob/master/components/hal/include/hal/spi_types.h) there is no such thing as SPI0 or SPI0_HOST.

And definitely SPI1 can't work as a general purpose SPI controller now.

Sorry for not testing all the cases, but please don't revert this PR.

**Comment by C47D** [comment]
Don't worry, thanks for reporting the problem, so if I understand it correctly, the C3 only have one SPI (SPI2) for user usage?

**Comment by arktrin** [comment]
> C3 only have one SPI (SPI2) for user usage?

Yeah, looks like that. I've tried to set SPI3_HOST for SPI bus and got:
```
E (369) spi: spi_bus_initialize(755): invalid host_id
```
I wonder where is SPI0_HOST or something related to SPI0 for ESP32-C3.

**Comment by C47D** [comment]
@arktrin I've created a new issue to keep track of this.

**Pull request merged**
