### PR TITLE
Merge develop branch into master

### LINKED ISSUE #146: Abandon `develop` branch
Merge `develop` branch into `master` and stop using it.

TODO: more details

### PR DESCRIPTION
**Pull request by tore-espressif**
Closes #146

### CODE REVIEW

**Comment by tore-espressif** [comment]
The CI has passed, but I will double check that nothing is broken locally tomorrow. (The CI is not very thorough yet)

**Comment by C47D** [comment]
Thanks for this. It will be interesting to see how we can update the drivers not updated so far.

**Comment by tore-espressif** [comment]
> It will be interesting to see how we can update the drivers not updated so far

Uf, I forgot about this. Branch `develop` is not working so we can't merge it now...

**Comment by C47D** [comment]
@tore-espressif I will update the drivers init functions so we can merge develop into master more easily

**Comment by rashedtalukder** [comment]
@tore-espressif @C47D it would appear that master and develop are diverging further and further apart. What's the plan and timeline to merging the two branches together? Right now, from me testing the two for my own needs, both have their set of issues that the other one fixes.

**Comment by tore-espressif** [comment]
@rashedtalukder Thank you very much for reminding me. I was quite busy lately, but I want to attend to it this week.

Could you please mention the issues you're experiencing, just so we don't forget anything?

**Comment by C47D** [comment]
Some of the drivers have been updated (passing a pointer to the registered `lv_disp_drv_t` as parameter to their init function), we will need to update the others.

Apart from that I think there will be no problem with merging develop into master.

I have been busy with day work and other stuff, and will be at least for two weeks, but let me know if you need any help.

**Comment by tore-espressif** [comment]
@C47D  There are **116** (!) commits that are in `develop` and not it `master`.

There are (only) **8** commits that are in `master` and not in `develop` (4 out of these 8 are reverts, see here: https://github.com/tore-espressif/lvgl_esp32_drivers/pull/6)

So it seems easier to me to fix `develop` once and for all and then force merge it into `master`. Do you agree?

**Comment by C47D** [comment]
Yes, I agree. Let's ban having long lived feature branches as well.

**Pull request closed without merging**
