### PR TITLE
Feature/color inversion

### LINKED ISSUE #38: ST7789 color inversion
For reasons unknown (missing git history) ST7789 driver inverts colors by default:

https://github.com/lvgl/lvgl_esp32_drivers/blob/master/lvgl_tft/st7789.c#L68

This has to be made configurable. 

This is more-or-less a feature request, as most of the LCD displays support color inversion.

### PR DESCRIPTION
**Pull request by tore-espressif**
Closes #38 

1.  Add color inversion option of ST7789 driver
2. Clean-up KConfig 'inversion' mess (first iteration)
3. Add .editorconfig file, for people who use [EditorConfig](https://editorconfig.org/)

(sorry for multiple changes in one PR.... again)

### CODE REVIEW

**Comment by C47D** [comment]
This also closes #36, isn't?

**Comment by tore-espressif** [comment]
oops, I have a separate https://github.com/lvgl/lvgl_esp32_drivers/pull/37 for that.
But I merged to master on my fork before merging it here, so you can see both changes in this PR...

**Comment by C47D** [comment]
No problem, I've merged the other PR first.

Are you still planning to send the PR editing the CMakeLists and Kconfig files?

**Comment by tore-espressif** [comment]
Next week hopefully :)

**Comment by C47D** [comment]
That's ok. There's an issue/request to make it possible to use multiple drivers on the same project. I was thinking on editing the CMakeLists.txt file from
```
if(CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9341)
    list(APPEND SOURCES "ili9341.c")
elseif(CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9481)
    list(APPEND SOURCES "ili9481.c")
else()
    message("DISPLAY CONTROLLER NOT DEFINED")
endif()
```

to something like this:
```
if(CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9341)
    list(APPEND SOURCES "ili9341.c")
endif()

if(CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9481)
    list(APPEND SOURCES "ili9481.c")
endif()
```

**Comment by tore-espressif** [comment]
Yes, I've seen the request, but it is going to be far more complicated than that.

Currently all KConfig options are global: display orientation, connection(I2C/SPI), pinout, color inversion.... A mere addition of the .c file to compilation list will not be sufficient.

Even LVGL itself is compiled with fixed resolution.

Let me know if there is something obvious that I'm missing

**Comment by C47D** [comment]
I didn't considered the Kconfig options being global, maybe we will need to open a new issue to talk about it.

**Pull request merged**
