### PR TITLE
LCD backlight controller

### PR DESCRIPTION
**Pull request by tore-espressif**
Related: https://github.com/lvgl/lvgl_esp32_drivers/pull/74

Changes in this PR:

- enable brightness control from menuconfig
- carve-out backlight control from TFT drivers
- support for multiple displays
- support for (future) runtime configuration

TODOs:

- [x] Carve out backlight control
- [x] Adapt existing display drivers
- [x] Update Kconfig
- [x] Compile with all existing drivers
- [x] Compile with IDF v 4.2 and below

### CODE REVIEW

**Comment by Rajssss** [comment]
Thanks :)

**Comment by C47D** [comment]
LGTM, can we add something about this in the README?

**Review by C47D — APPROVED** [review]
LGTM!

**Comment by tore-espressif** [comment]
> can we add something about this in the README?

Sure, will do

**Comment by tore-espressif** [comment]
@C47D Readme updated.

Give me a thumb up and I'll merge it.
(I'd like to have me first merge as 'Collaborator', lol)

**Comment by C47D** [comment]
It's all yours @tore-espressif , great job! 🥳

**Pull request merged**
