### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by tore-espressif**
Closes https://github.com/lvgl/lvgl_esp32_drivers/issues/146

### CODE REVIEW

**Comment by tore-espressif** [comment]
@C47D This PR resolves conflicts between master and develop. It can be successfully build (check GH actions)

I'll have to test in on HW before merging, though

**Comment by tore-espressif** [comment]
Update: tested and working with ESP32S2 + ST7789 + LVGL v8.

I understand that the other drivers were not updated to LVGL v8 yet.

**Comment by C47D** [comment]
Hi @tore-espressif, as far as I remember that particular driver is the only one that works with both LVGL v7 and v8.

Thanks for taking the time to solve this issue, I know is not very fun to do :)

**Comment by tore-espressif** [comment]
Well, I caused the whole problem, it's shame that it took me so long.

If this gets merged into develop, do you want to merge develop to master ASAP? As far as I understand it, there will be inconsistencies between drivers.

(Related discussion https://github.com/lvgl/lvgl_esp32_drivers/pull/188)

**Comment by C47D** [comment]
Hi, don't worry. We could merge develop into master and firstly fix compilation errors. Then update drivers gradually. What do you think?

**Comment by tore-espressif** [comment]
Fair enough 👍

**Comment by C47D** [comment]
Feel free to merge this.

**Pull request merged**
