### PR TITLE
fix spi names

### PR DESCRIPTION
**Pull request by tore-espressif**

### CODE REVIEW

**Comment by arktrin** [comment]
This commit breaks my hardware configuration with ESP32-C3 + ST7789 based display. At least SPI2_HOST won't work at all.

**Comment by tore-espressif** [comment]
Reverted. I'll double check next week. Sorry for the troubles :/

**Comment by C47D** [comment]
@arktrin did the initialization of the SPI master failed? I don't have any C3 module to test.

**Comment by arktrin** [comment]
I'm not sure what is happening, it compiles without any errors but SPI doesn't work at all.

**Comment by C47D** [comment]
It's been a while since I touch the SPI code, but maybe we should add some logging and use idf monitor to try found the issue.

**Comment by arktrin** [comment]
Sorry for delay, I'm getting this error for my ESP32-C3:
`spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc`

**Comment by arktrin** [comment]
Just for testing I've replaced `spi_bus_initialize(host, &buscfg, (spi_dma_chan_t)dma_channel);`   with `spi_bus_initialize(host, &buscfg, 0);` . Now spi configured and dma is not used at all but I'm getting another error:
`E (1584) spi_master: check_trans_valid(689): txdata transfer > host maximum`

**Comment by arktrin** [comment]
Not looking in the right place, `spi_bus_initialize(host, &buscfg, 3);`  is the proper initialization for ESP32-C3 with auto-dma.

**Comment by arktrin** [comment]
I've done PR #153 with a slight change to workaround the problem.

**Pull request merged**
