### PR TITLE
fix SPI names for touch

### PR DESCRIPTION
**Pull request by arktrin**
with ESP32-C3 specific auto-dma proper selection

### CODE REVIEW

**Comment by arktrin** [comment]
Just a slight change of the previous commit with specific auto-dma selection for ESP32-C3. Sorry for the auto-indent of my sublime editor.

**Review by C47D — COMMENTED** [review]
Can we replace the hardcoded 3 with `SPI_DMA_CH_AUTO`?

**Comment by arktrin** [comment]
> Can we replace the hardcoded 3 with `SPI_DMA_CH_AUTO`?

Done!

**Review by tore-espressif — APPROVED** [review]
LGTM!

**Review by C47D — APPROVED** [review]

**Pull request merged**
