### PR TITLE
st7735s: Added brightness control though LED pin

### PR DESCRIPTION
**Pull request by Rajssss**
-> Uses LED(Backlight) Pin as PWM to control the brightness

Signed-off-by: Rajssss <sssraj.sssraj@gmail.com>

### CODE REVIEW

**Comment by tore-espressif** [comment]
Hello @Rajssss 
Thank you very much for you PR ! Backlight control is something that is needed by many users.

However, I don't like adding this feature to a specific display driver (ST7735S), because it is not specific to this driver, but rather common for (almost) all displays.

I'd like to carve-out the backlight control from our current code and create a component, that could be as simple as the code you pushed. But reusable for all displays.

Let me know what you think

**Comment by Rajssss** [comment]
> Hello @Rajssss
> Thank you very much for you PR ! Backlight control is something that is needed by many users.
> 
> However, I don't like adding this feature to a specific display driver (ST7735S), because it is not specific to this driver, but rather common for (almost) all displays.
> 
> I'd like to carve-out the backlight control from our current code and create a component, that could be as simple as the code you pushed. But reusable for all displays.
> 
> Let me know what you think

I agree, that will be the best, but I don't know about all other controllers supported by this project. But, If it's all about a backlight pin then it can be done, though right now I don't have any idea of a separate component. I will look into it, but not sure how much time it will take.

**Comment by tore-espressif** [comment]
Best and future-proof solution would be to create new component `esp_lcd_backlight.c/.h`. So if you are willing to create it, that would be great.

If not, we can merge it as it is, and refactor the code in upcoming 2.0.0 refactoring #72

**Comment by Rajssss** [comment]
> Best and future-proof solution would be to create new component `esp_lcd_backlight.c/.h`. So if you are willing to create it, that would be great.
> 
> If not, we can merge it as it is, and refactor the code in upcoming 2.0.0 refactoring #72

Ok, I will try to do that by this weekend.

**Comment by Rajssss** [comment]
@tore-espressif please review it, I have not edited the kconfig for now, is it required?

**Comment by C47D** [comment]
It seems to me it's going in the right direction, thanks @Rajssss, @tore-espressif do you think we need to add a `choice` with the different back-light control options? We could have:
- no back-light control
- on/off back-light control
- pwm back-light control (this one)

**Comment by Rajssss** [comment]
> It seems to me it's going in the right direction, thanks @Rajssss, @tore-espressif do you think we need to add a `choice` with the different back-light control options? We could have:
> 
>     * no back-light control
> 
>     * on/off back-light control
> 
>     * pwm back-light control (this one)

I like the idea, but in a long run maybe, as we have to test different displays, maybe.

**Comment by C47D** [comment]
@Rajssss Thanks :)

**Comment by tore-espressif** [comment]
LGTM!

**Comment by Rajssss** [comment]
> The only missing thing seems to be the Kconfig. Apart from that, LGTM!
> 
> > I like the idea, but in a long run maybe, I will see how much I can do this weekend
> 
> Understand. We can merge it with pwm only now and fine tune it later.

Thanks :)

**Comment by C47D** [comment]
Sorry for the late reply 😊

**Comment by tore-espressif** [comment]
Oh, sorry, I forgot about this PR. We still need to add Kconfig option CONFIG_LV_ENABLE_BACKLIGHT_CONTROL.

I'll add it today

**Pull request merged**
