### PR TITLE
Remove & operator when passing display driver to lv_disp_flush_ready

### LINKED ISSUE #81: Extra address-of operator in lv_disp_flush_ready(disp-driver)
https://github.com/lvgl/lvgl_esp32_drivers/blob/7d0bbe8ce57eece8abd955fceadc07c9bce7c3b4/lvgl_tft/disp_spi.c#L313

This line fails to compile for me, until I remove the ampersand.

### PR DESCRIPTION
**Pull request by C47D**
Closes #81

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
In retrospect we probably should have renamed `disp->driver` to `disp->drv_p` in v8, which would force anyone not using warnings to still take a look at this. :laughing:

**Comment by kisvegabor** [comment]
> In retrospect we probably should have renamed disp->driver to disp->drv_p in v8, which would force anyone not using warnings to still take a look at this. laughing

Good idea :smile:

**Review by kisvegabor — APPROVED** [review]

**Comment by C47D** [comment]
I'm searching how to enable more warnings on the ESP-IDF projects, can we merge this now?

**Comment by kisvegabor** [comment]
Sure!

**Pull request merged**
