### PR TITLE
Don't call backlight function when backlight is disabled

### PR DESCRIPTION
**Pull request by tore-espressif**
Backlight could not be turned off via Kconfig

### CODE REVIEW

**Comment by tore-espressif** [comment]
Changes like this will be merged to branch `develop` in the future...

**Comment by kisvegabor** [comment]
> Changes like this will be merged to branch develop in the future...

Do you already have a suitable branching strategy for this repo?

**Comment by C47D** [comment]
> Do you already have a suitable branching strategy for this repo?

@kisvegabor This comment might answer that https://github.com/lvgl/lvgl_esp32_drivers/pull/100#issuecomment-898409254

**Comment by kisvegabor** [comment]
Thanks, Carlos.

**Comment by C47D** [comment]
@tore-espressif Feel free to merge this.

**Pull request merged**
